CREATE SCHEMA IF NOT EXISTS `publishing`;

USE `publishing`;

CREATE TABLE IF NOT EXISTS Books (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ISBN VARCHAR(255) NOT NULL,
  Name VARCHAR(255),
  Pages INT,
  Publish_date DATE,
  UNIQUE (ISBN)
);

CREATE TABLE IF NOT EXISTS Authors (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Surname VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Genres (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
	UNIQUE (Name)
);

CREATE TABLE IF NOT EXISTS Books_Authors (
  Book_ID INT,
  Author_ID INT,
  FOREIGN KEY (Book_ID) REFERENCES Books(ID) ON DELETE CASCADE,
  FOREIGN KEY (Author_ID) REFERENCES Authors(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Books_Genres (
  Book_ID INT,
  Genre_ID INT,
  FOREIGN KEY (Book_ID) REFERENCES Books(ID) ON DELETE CASCADE,
  FOREIGN KEY (Genre_ID) REFERENCES Genres(ID) ON DELETE CASCADE
);

CREATE VIEW Books_Authors_Genres AS
SELECT b.*,
  GROUP_CONCAT(DISTINCT CONCAT(a.Name, ' ', a.Surname) ORDER BY CONCAT(a.Name, ' ', a.Surname) SEPARATOR ', ') AS Authors,
  GROUP_CONCAT(DISTINCT g.Name ORDER BY g.Name SEPARATOR ', ') AS Genres
FROM Books b
LEFT JOIN Books_Authors ba ON b.ID = ba.Book_ID
LEFT JOIN Authors a ON a.ID = ba.Author_ID
LEFT JOIN Books_Genres bg ON b.ID = bg.Book_ID
LEFT JOIN Genres g ON bg.Genre_ID = g.ID
GROUP BY b.ID;